#!/usr/bin/env python3
"""
Extract baseline design cues from PowerPoint templates packed inside ZIP files.

This script scans an assets directory for .zip files, finds embedded .pptx files,
and reports theme colors, font scheme, and basic layout counts.
"""

from __future__ import annotations

import argparse
import io
import re
from pathlib import Path
from typing import Dict, List, Optional
import xml.etree.ElementTree as ET
import zipfile


def local_name(tag: str) -> str:
    return tag.rsplit("}", 1)[-1]


def find_embedded_pptx_bytes(container_zip: Path) -> Optional[bytes]:
    with zipfile.ZipFile(container_zip, "r") as zf:
        candidates = [n for n in zf.namelist() if n.lower().endswith(".pptx")]
        if not candidates:
            return None
        candidates.sort(key=lambda name: (name.count("/"), len(name)))
        return zf.read(candidates[0])


def parse_theme(xml_bytes: bytes) -> Dict[str, object]:
    root = ET.fromstring(xml_bytes)

    colors: List[str] = []
    clr_scheme = root.find(".//{*}clrScheme")
    if clr_scheme is not None:
        for child in list(clr_scheme):
            slot = local_name(child.tag)
            color_value = ""
            for node in list(child):
                if "val" in node.attrib:
                    color_value = node.attrib["val"]
                    break
                if "lastClr" in node.attrib:
                    color_value = node.attrib["lastClr"]
                    break
            if color_value:
                colors.append(f"{slot}:{color_value}")

    major_font = root.find(".//{*}majorFont/{*}latin")
    minor_font = root.find(".//{*}minorFont/{*}latin")
    major_typeface = major_font.attrib.get("typeface", "") if major_font is not None else ""
    minor_typeface = minor_font.attrib.get("typeface", "") if minor_font is not None else ""

    return {
        "colors": colors,
        "major_font": major_typeface or "unknown",
        "minor_font": minor_typeface or "unknown",
    }


def analyze_pptx_bytes(pptx_bytes: bytes) -> Dict[str, object]:
    with zipfile.ZipFile(io.BytesIO(pptx_bytes), "r") as pz:
        names = pz.namelist()

        slide_count = len(
            [n for n in names if re.match(r"^ppt/slides/slide\d+\.xml$", n)]
        )
        layout_count = len(
            [n for n in names if re.match(r"^ppt/slideLayouts/slideLayout\d+\.xml$", n)]
        )
        media_count = len([n for n in names if n.startswith("ppt/media/")])

        theme_name = next((n for n in names if n.startswith("ppt/theme/theme")), None)
        theme_data = {"colors": [], "major_font": "unknown", "minor_font": "unknown"}
        if theme_name:
            try:
                theme_data = parse_theme(pz.read(theme_name))
            except ET.ParseError:
                pass

    return {
        "slide_count": slide_count,
        "layout_count": layout_count,
        "media_count": media_count,
        **theme_data,
    }


def render_report(items: List[Dict[str, object]]) -> str:
    lines = [
        "# Template Style Summary",
        "",
        "Generated by `scripts/extract_design_cues.py`.",
        "",
    ]

    if not items:
        lines.append("No analyzable template decks found.")
        lines.append("")
        return "\n".join(lines)

    for item in items:
        lines.append(f"## {item['zip_name']}")
        if item.get("error"):
            lines.append(f"- status: {item['error']}")
            lines.append("")
            continue

        lines.append(f"- slides: {item['slide_count']}")
        lines.append(f"- slide layouts: {item['layout_count']}")
        lines.append(f"- media assets: {item['media_count']}")
        lines.append(f"- major font: {item['major_font']}")
        lines.append(f"- minor font: {item['minor_font']}")
        colors = item["colors"] if item["colors"] else ["none detected"]
        lines.append("- color slots:")
        for color in colors:
            lines.append(f"  - {color}")
        lines.append("")

    return "\n".join(lines)


def main() -> None:
    parser = argparse.ArgumentParser(description="Extract style cues from ZIP templates.")
    parser.add_argument(
        "--assets-dir",
        type=Path,
        default=Path(__file__).resolve().parents[1] / "assets",
        help="Directory containing template ZIP files.",
    )
    parser.add_argument(
        "--out",
        type=Path,
        default=Path(__file__).resolve().parents[1] / "references" / "template-style-summary.md",
        help="Output markdown report path.",
    )
    args = parser.parse_args()

    assets_dir = args.assets_dir
    out_path = args.out
    out_path.parent.mkdir(parents=True, exist_ok=True)

    reports: List[Dict[str, object]] = []

    for zip_path in sorted(assets_dir.glob("*.zip")):
        entry: Dict[str, object] = {"zip_name": zip_path.name}
        try:
            pptx_bytes = find_embedded_pptx_bytes(zip_path)
            if pptx_bytes is None:
                entry["error"] = "no embedded .pptx found in container zip"
            else:
                entry.update(analyze_pptx_bytes(pptx_bytes))
        except Exception as exc:  # noqa: BLE001
            entry["error"] = f"failed to analyze: {exc}"
        reports.append(entry)

    out_path.write_text(render_report(reports))
    print(f"[OK] Wrote style summary to {out_path}")


if __name__ == "__main__":
    main()
